Adds garage project
renekounkou/RkquintrixTraining pull request #2
Opened 2022-04-05 21:05 UTC by renekounkou

Please review.

2022-04-05 21:07 UTC, renekounkou commented
Please review

2022-04-09 14:28 UTC, dentaylor requested changes
Resolve the comments then push your changes to the same branch.

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/main/java/garage/com/LargeEngine.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/main/java/garage/com/LargeEngine.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/Car.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/Car.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/Car.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/Car.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/CarTests.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/CarTests.java
> +
RW (remove whitespace)

2022-04-09 14:28 UTC, dentaylor commented on garage.com/src/test/java/Car.java
> +		return odometer;
Use 'this' keyword

Ex: return this.odometer

2022-04-10 13:01 UTC, closed without merging