Adds a new Test "Java Exercises" to garage.com.
renekounkou/RkquintrixTraining pull request #3
Opened 2022-04-08 18:07 UTC by renekounkou

Please review.

2022-04-15 16:00 UTC, dentaylor requested changes
Resolve comments. All tests should pass. Add assertions where missing.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  boolean expectedResult = true;
Move this to the Arrange section (the top of the method)

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(compare);
Remove this

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>    public void comparaTwoValue() {
Fix spelling

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  boolean expectedResult = false;
Move this to the Arrange section

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(result);
Remove this.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(totalAge, expectedResult, "total age is equal to 75");
Assertion should be outside of the IF statement block. The assertion may not be reached due to the way it is currently written.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(totalAge, expectedResult, "total age is equal to 75");
Same as above.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>    public void demonstrateUnaryOperstors() {
Check spelling.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(z);
Remove println's

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  int x = 3;
Simplify this a bit. It's difficult to understand.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(result);
Remove println's

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(compareHour, expectedResult, "The Morning hour is different to the Afternoon hour");
This does demonstrate if statements but the assertion should assert that the if statements were executed.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  		  assertEquals(passGrade, expectedResult, "If grade is eual to 80, you passed");
This does demonstrate if statements but the assertion should assert that the if statements were executed.

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
> -
Needs an assertion

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  }
Needs an assertion

2022-04-15 16:00 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(colors, expectedResult);
This assertion will fail.

2022-04-17 13:26 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  boolean expectedResult = true;
Done

2022-04-17 13:27 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(compare);
Done

2022-04-17 13:27 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>    public void comparaTwoValue() {
Done

2022-04-17 13:27 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  boolean expectedResult = false;
Done

2022-04-17 13:28 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(result);
Done

2022-04-17 13:28 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(totalAge, expectedResult, "total age is equal to 75");
Done

2022-04-17 13:29 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(totalAge, expectedResult, "total age is equal to 75");
Resolved

2022-04-17 13:29 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>    public void demonstrateUnaryOperstors() {
Resolved

2022-04-17 13:29 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(z);
Resolved

2022-04-17 13:30 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  int x = 3;
Resolved

2022-04-17 13:30 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  System.out.println(result);
Resolved

2022-04-17 13:30 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(compareHour, expectedResult, "The Morning hour is different to the Afternoon hour");
Resolved

2022-04-17 13:30 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  		  assertEquals(passGrade, expectedResult, "If grade is eual to 80, you passed");
Resolved

2022-04-17 13:33 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  }
I wrote the assertion inside the try block. Do I have to write the assertion in the catch block?

2022-04-17 13:35 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  assertEquals(colors, expectedResult);
The test passed after running it.

2022-04-18 00:13 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  }
Write it outside of the try/catch block

2022-04-18 00:14 UTC, dentaylor commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
> -
Move the assertion outside of the for loops

2022-04-18 00:14 UTC, dentaylor requested changes
See latest comments

2022-04-22 02:22 UTC, renekounkou commented on garage.com/src/test/java/com/garage/JavaExercisesTest.java
>  	  }
Resolved

2022-04-22 02:24 UTC, renekounkou commented
The assertion has been moved outside of the for loops.

2022-04-22 21:40 UTC, dentaylor approved these changes

2022-04-22 23:06 UTC, merged