Adds a new Test ReadFromCSVFileTest to the garage.com project.
renekounkou/RkquintrixTraining pull request #4
Opened 2022-04-11 01:26 UTC by renekounkou

2022-04-21 13:11 UTC, dentaylor requested changes

2022-04-21 13:11 UTC, dentaylor commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest.java
> +		  assertEquals(csvFilePath, expectedResult);
Assertion should not be in this loop

2022-04-21 13:11 UTC, dentaylor commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest.java
> +	  }
Fix indentation

2022-04-21 13:11 UTC, dentaylor commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest1.java
> +
Remove extra lines (43 & 44)

2022-04-22 02:36 UTC, renekounkou commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest.java
> +		  assertEquals(csvFilePath, expectedResult);
Moved the assertion outside of the loop.

2022-04-22 02:36 UTC, renekounkou commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest.java
> +	  }
Resolved.

2022-04-22 02:37 UTC, renekounkou commented on garage.com/src/test/java/com/garage/ReadFromCSVFileTest1.java
> +
Resolved.

2022-04-22 21:41 UTC, dentaylor approved these changes

2022-04-22 23:05 UTC, merged